"""removed private key and public key from user model

Revision ID: 1883724f0df2
Revises: 3368c78fb6c3
Create Date: 2024-03-05 18:49:18.714557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1883724f0df2'
down_revision = '3368c78fb6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('public_key')
        batch_op.drop_column('private_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('public_key', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
